### ISSUE TITLE
Sunset interplay

### ISSUE THREAD

**Issue by ignasi35** [playframework/interplay#150]
It'd be good to stop depending on Interplay. Maintaining scala cross versions, having to move upstream (from play-foo to interplay) for each imrpovement, etc... is becoming more of a blocker than a benefit.

Each downstream project should inherit whichever pieces of interplay it deems necessary and maintain them separately. Here's a list of projects using interplay:

- [x] playframework
https://github.com/playframework/playframework/pull/11987
- [x] omnidoc
https://github.com/playframework/omnidoc/pull/268
- [x] play-doc
https://github.com/playframework/play-doc/pull/206
- [x] scalatestplus-play
https://github.com/playframework/scalatestplus-play/pull/447
- [x] play-socket.io
https://github.com/playframework/play-socket.io/pull/214
- [x] play-slick
https://github.com/playframework/play-slick/pull/773
- [x] anorm
https://github.com/playframework/anorm/pull/587

No longer use `interplay`:

1.  - ~play-json~ --> already uses its own copy of `Omnidoc.scala`
2.  - ~twirl~ --> already uses its own copy of `Omnidoc.scala`
3.  - ~play-soap~

EOL projects that refer to `interplay` (false positives):

1.  - ~play-native-loader~ --> archived EOL
2.  - ~play-spring-loader~ --> archived EOL
3.  - ~play-enhancer~ --> archived EOL
4.  - ~play-iteratees~ --> archived EOL

**Comment by ihostage** [comment]
@mkurz I finished the work on this. Can you review? 😉 
Or just we can merge these PR's without review and I will fix problems in the future if something is wrong at release.

**Comment by mkurz** [comment]
Done, repo will be archived now.
