### ISSUE TITLE
Support sbt 1.0

### ISSUE THREAD

**Issue by marcospereira** [playframework/interplay#27]
We should cross build to sbt 0.13 and 1.0.

It could be a good idea to also bump version to 2.0.0 since this is a major update.

**Comment by nafg** [comment]
What's the status of this?

**Comment by marcospereira** [comment]
See #32. I'm basically finishing some test details. :-)

**Comment by wsargent** [comment]
Addressed by https://github.com/playframework/interplay/pull/34 but not published to Sonatype yet -- @marcospereira  1.4.0?

**Comment by marcospereira** [comment]
@wsargent, published as 1.3.8.
