### ISSUE TITLE
Drop cross-building for sbt 0.13

### ISSUE THREAD

**Issue by ignasi35** [playframework/interplay#70]
All users of `interplay` should have already migrated to sbt 1.x so this codebase no longer needs to cross-publish for sbt 0.13.

e.g. https://github.com/playframework/interplay/blob/683f711937365bcbfcd00d4a1eabae1a1636a350/build.sbt#L16-L31

or compat code in `src/main/scala-sbt-0.13`

**Comment by dwijnand** [comment]
Rename to "Drop cross-building" as Interplay will still need to support building sbt 0.13 plugins, even if the builds are sbt 1.x only.
