### ISSUE TITLE
Wrong choice of arguments when scalaBin is 2.13

### ISSUE THREAD

**Issue by ignasi35** [playframework/interplay#90]
in:

https://github.com/playframework/interplay/blob/07295bc68dfeab536d1552f48db640725cc92d9c/src/main/scala/interplay/PlayBuildBase.scala#L158-L161

The defaults fallback to `scala210`. This is wrong when `scalaBinVersion` is `2.13`.

**Comment by ennru** [comment]
This bit is long gone now.
